"""
config.py
Central configuration for the Antarctic Station Intelligence Platform (PolarOps AI).

All paths, station metadata, thresholds and weights used across the
application live here so behaviour can be tuned without touching module code.
"""

import os

# ---------------------------------------------------------------------------
# PATHS
# ---------------------------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

DATA_DIR = os.path.join(BASE_DIR, "data")
RAW_NCPOR_DIR = os.path.join(DATA_DIR, "raw", "ncpor")
RAW_EXTERNAL_DIR = os.path.join(DATA_DIR, "raw", "external")
RAW_IMD_DIR = os.path.join(DATA_DIR, "raw", "imd")
PROCESSED_DIR = os.path.join(DATA_DIR, "processed")
SIMULATED_DIR = os.path.join(DATA_DIR, "simulated")

DATABASE_DIR = os.path.join(BASE_DIR, "database")
DATABASE_PATH = os.path.join(DATABASE_DIR, "antarctic.db")

MODELS_DIR = os.path.join(BASE_DIR, "models")
LOGS_DIR = os.path.join(BASE_DIR, "logs")

for _d in (DATA_DIR, RAW_NCPOR_DIR, RAW_IMD_DIR, RAW_EXTERNAL_DIR, PROCESSED_DIR,
           SIMULATED_DIR, DATABASE_DIR, MODELS_DIR, LOGS_DIR):
    os.makedirs(_d, exist_ok=True)

# ---------------------------------------------------------------------------
# STATIONS
# ---------------------------------------------------------------------------
STATIONS = {
    "Maitri": {
        "full_name": "Maitri Research Station",
        "latitude": -70.7660,
        "longitude": 11.7333,
        "region": "Schirmacher Oasis, Queen Maud Land",
        "established": 1989,
    },
    "Bharati": {
        "full_name": "Bharati Research Station",
        "latitude": -69.4082,
        "longitude": 76.1913,
        "region": "Larsemann Hills, Prydz Bay",
        "established": 2012,
    },
}

# ---------------------------------------------------------------------------
# DATA PROVENANCE CATEGORIES  (see DATA_SOURCES.md)
# ---------------------------------------------------------------------------
REAL_OBSERVED = "REAL_OBSERVED"
REAL_REFERENCE = "REAL_REFERENCE"
SIMULATED_DEMO = "SIMULATED_DEMO"
REAL_FORECAST = "REAL_FORECAST"
MODEL_PREDICTION = "MODEL_PREDICTION"

# DATA MODE / SOURCE SETTINGS
# REAL mode uses NCPOR live/local observations and official IMD forecast files when present.
# DEMO mode intentionally uses the deterministic simulator for the hackathon storyline.
DATA_MODE = os.getenv("POLAROPS_DATA_MODE", "REAL").upper()

# Optional AI agent configuration. Environment variables are preferred; a local
# .env file is supported for hackathon convenience and should never be committed.
def _load_local_env():
    env_path = os.path.join(BASE_DIR, ".env")
    if not os.path.exists(env_path):
        return
    try:
        with open(env_path, "r", encoding="utf-8") as fh:
            for raw in fh:
                line = raw.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, value = line.split("=", 1)
                key, value = key.strip(), value.strip().strip('\"').strip("'")
                os.environ.setdefault(key, value)
    except OSError:
        pass

_load_local_env()
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-5.6-luna")
NCPOR_LIVE_ENABLED = os.getenv("NCPOR_LIVE_ENABLED", "1") == "1"
NCPOR_LIVE_TIMEOUT_SECONDS = int(os.getenv("NCPOR_LIVE_TIMEOUT_SECONDS", "2"))

# NOTE ON DATA ACCESS:
# This build environment has no outbound internet access, so live download
# from the NCPOR / National Polar Data Centre (NPDC) portals could not be
# performed while generating this project. Station coordinates and names
# above are REAL_REFERENCE (public knowledge). All time-series telemetry
# shipped with this project (weather, equipment, energy, inventory,
# logistics) is SIMULATED_DEMO, generated by src/data/simulator.py using
# physically plausible relationships (see ARCHITECTURE.md). The ingestion
# layer (src/data/ncpor_loader.py) is built to accept a real NCPOR CSV
# export and will automatically switch a station's weather data to
# REAL_OBSERVED once such a file is placed in data/raw/ncpor/.

# ---------------------------------------------------------------------------
# RISK ENGINE WEIGHTS (must sum to 1.0)
# ---------------------------------------------------------------------------
RISK_WEIGHTS = {
    "weather": 0.25,
    "equipment": 0.25,
    "energy": 0.20,
    "inventory": 0.15,
    "logistics": 0.10,
    "communication": 0.05,
}

RISK_LEVELS = [
    (0, 25, "LOW"),
    (25, 50, "MEDIUM"),
    (50, 75, "HIGH"),
    (75, 101, "CRITICAL"),
]

# ---------------------------------------------------------------------------
# WEATHER RISK THRESHOLDS
# ---------------------------------------------------------------------------
WEATHER_THRESHOLDS = {
    "temp_c_low": -35.0,       # below this: high contribution
    "temp_c_moderate": -25.0,
    "wind_kmh_high": 90.0,     # gale-force+
    "wind_kmh_moderate": 60.0,
    "pressure_hpa_change_high": 8.0,   # hPa change over 6h window
}

# ---------------------------------------------------------------------------
# EQUIPMENT / PREDICTIVE MAINTENANCE
# ---------------------------------------------------------------------------
EQUIPMENT_LIST = [
    {"id": "GEN-01", "name": "Generator G-01", "station": "Maitri", "category": "Power"},
    {"id": "GEN-02", "name": "Generator G-02", "station": "Maitri", "category": "Power"},
    {"id": "HTG-01", "name": "Heating Plant H-01", "station": "Maitri", "category": "Heating"},
    {"id": "COM-01", "name": "Comms Array C-01", "station": "Maitri", "category": "Communication"},
    {"id": "GEN-11", "name": "Generator G-11", "station": "Bharati", "category": "Power"},
    {"id": "GEN-12", "name": "Generator G-12", "station": "Bharati", "category": "Power"},
    {"id": "HTG-11", "name": "Heating Plant H-11", "station": "Bharati", "category": "Heating"},
    {"id": "COM-11", "name": "Comms Array C-11", "station": "Bharati", "category": "Communication"},
]

ANOMALY_CONTAMINATION = 0.08  # expected fraction of anomalous readings for IsolationForest

# ---------------------------------------------------------------------------
# INVENTORY
# ---------------------------------------------------------------------------
INVENTORY_ITEMS = [
    {"item": "Generator Spare Filters", "category": "Critical Spare", "station": "Maitri",
     "stock": 8, "min_stock": 5, "daily_usage": 0.35, "lead_time_days": 90, "criticality": "Very High"},
    {"item": "Medical Supplies Kit", "category": "Medical", "station": "Maitri",
     "stock": 20, "min_stock": 10, "daily_usage": 0.15, "lead_time_days": 60, "criticality": "High"},
    {"item": "Diesel Fuel (kL)", "category": "Fuel", "station": "Maitri",
     "stock": 140, "min_stock": 60, "daily_usage": 1.8, "lead_time_days": 120, "criticality": "Very High"},
    {"item": "General Consumables", "category": "Consumable", "station": "Maitri",
     "stock": 300, "min_stock": 100, "daily_usage": 4.0, "lead_time_days": 90, "criticality": "Medium"},
    {"item": "Generator Spare Filters", "category": "Critical Spare", "station": "Bharati",
     "stock": 12, "min_stock": 5, "daily_usage": 0.30, "lead_time_days": 100, "criticality": "Very High"},
    {"item": "Medical Supplies Kit", "category": "Medical", "station": "Bharati",
     "stock": 15, "min_stock": 10, "daily_usage": 0.12, "lead_time_days": 70, "criticality": "High"},
    {"item": "Diesel Fuel (kL)", "category": "Fuel", "station": "Bharati",
     "stock": 95, "min_stock": 60, "daily_usage": 1.6, "lead_time_days": 130, "criticality": "Very High"},
    {"item": "General Consumables", "category": "Consumable", "station": "Bharati",
     "stock": 250, "min_stock": 100, "daily_usage": 3.5, "lead_time_days": 100, "criticality": "Medium"},
]

# ---------------------------------------------------------------------------
# SIMULATION CONTROL
# ---------------------------------------------------------------------------
SIM_RANDOM_SEED = 42          # deterministic base simulation -> reproducible demo
HISTORY_DAYS = 7              # compact 7-day operational history for faster dashboard startup
READINGS_PER_DAY = 24         # hourly readings

DEMO_SCENARIOS = ["NORMAL", "EXTREME_WEATHER", "EQUIPMENT_ANOMALY", "RESOURCE_PRESSURE", "COMPOUND_EMERGENCY"]

# ---------------------------------------------------------------------------
# UI COLOR SYSTEM (used consistently across every dashboard page)
# ---------------------------------------------------------------------------
COLORS = {
    "LOW": "#2E7D32",        # green
    "NORMAL": "#2E7D32",
    "OK": "#2E7D32",
    "MEDIUM": "#F9A825",     # amber
    "WATCH": "#F9A825",
    "HIGH": "#EF6C00",       # orange
    "CRITICAL": "#C62828",   # red
    "OFFLINE": "#616161",    # grey
    "INFO": "#1565C0",       # blue
    "background": "#0E1117",
    "card": "#161B22",
    "text": "#E6E6E6",
}
