import streamlit as st
from src.utils.ui_helpers import inject_base_css, render_sidebar
st.set_page_config(page_title="SIH Solution Overview — Polar Twin Sentinel", page_icon="◈", layout="wide", initial_sidebar_state="expanded"); inject_base_css(); render_sidebar()
st.markdown('<div class="pts-hero"><div class="pts-kicker">SIH 2026 • PROPOSED SOLUTION</div><div class="pts-title">DIGITAL TWIN OF MAITRI + BHARATI</div><div class="pts-sub">Real environmental observations + IMD forecast intelligence + AI prediction + what-if simulation + offline support.</div></div>',unsafe_allow_html=True)
st.markdown('## PROPOSED SOLUTION')
items=[('Create the Digital Twin','Build a live virtual representation of Maitri and Bharati research stations.'),('Collect real data','Use NCPOR observations and keep IMD Polar WRF forecasts as a separate forecast stream.'),('Unify operations','Combine environmental, energy, equipment, logistics and resource signals in one platform.'),('AI prediction','Detect unusual conditions, predict risks and forecast energy needs.'),('What-if simulation','Test possible situations and compare projected outcomes before action.'),('Alerts + recommendations','Prioritize issues and provide explainable recommended actions with human approval.')]
for a,b in items: st.markdown(f'<div class="source-card" style="margin-bottom:10px"><div class="source-title">{a}</div><div class="source-copy">{b}</div></div>',unsafe_allow_html=True)
st.markdown('## INNOVATION'); st.markdown('<div class="impact"><div class="impact-big">REAL DATA + DIGITAL TWIN + AI PREDICTION + WHAT-IF SIMULATION + OFFLINE SUPPORT</div></div>',unsafe_allow_html=True)
st.markdown('## TECHNICAL APPROACH'); flow=['NCPOR REAL OBSERVATIONS','IMD POLAR WRF','DATA PROCESSING','DIGITAL TWIN','AI / ML','WHAT-IF','DASHBOARD + ALERTS']; st.markdown('<div class="panel"><div class="flow">'+''.join([f'<span class="flow-step">{x}</span><span class="flow-arrow">→</span>' for x in flow[:-1]])+f'<span class="flow-step">{flow[-1]}</span></div></div>',unsafe_allow_html=True); st.markdown('**Technology:** React | Python | FastAPI | AI/ML | PostgreSQL | IoT | Docker — target production stack; this prototype runs locally in Streamlit/Python.')
cols=st.columns(2)
with cols[0]: st.markdown('<div class="panel"><div class="panel-title">WHY FEASIBLE</div><ul><li>Real NCPOR data for environmental validation.</li><li>Official IMD Polar WRF export adapter.</li><li>Synthetic data only for non-public equipment/energy/logistics telemetry.</li><li>Offline cache for connectivity problems.</li><li>Human approval before important actions.</li></ul></div>',unsafe_allow_html=True)
with cols[1]: st.markdown('<div class="panel"><div class="panel-title">CHALLENGES → SOLUTIONS</div><ul><li>Poor connectivity → Edge/Offline Processing</li><li>Missing data → Data Validation</li><li>Wrong prediction → Confidence Score + Human Approval</li><li>Security risks → Authentication + Encryption in production deployment</li></ul></div>',unsafe_allow_html=True)
st.markdown('## IMPACT & BENEFITS'); cs=st.columns(6)
for c,t,d in zip(cs,['🧑‍🚀 Safety','⚡ Energy','🔧 Maintenance','📦 Logistics','🌍 Environment','🔬 Research'],['Detect risks early','Predict energy needs','Reduce downtime','Plan supplies','Monitor changes','Unify analysis']):
    with c: st.markdown(f'<div class="source-card"><div class="source-title">{t}</div><div class="source-copy">{d}</div></div>',unsafe_allow_html=True)
st.markdown('<div class="impact" style="margin-top:14px"><div class="impact-big">CURRENT: MONITOR → PROBLEM → RESPOND</div><div class="impact-small">OUR SOLUTION: MONITOR → PREDICT → PREVENT</div></div>',unsafe_allow_html=True)
